// Flow Scheduler 1.0.0 — deterministic temporal arbitration runtime.
// Copyright 2026 Summon Software Labs.
// Licensed under the Apache License, Version 2.0.
//
// Synthetic scheduling benchmark. Every number printed here measures completed
// work, never enqueue or admission counts, and the population is generated by
// this program rather than observed on a network. Output is therefore labelled
// SYNTHETIC and must never be presented as a physical-network measurement.

#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <string>
#include <vector>

#include "flow_scheduler/bench.hpp"
#include "flow_scheduler/version.hpp"

namespace {

using namespace flow_scheduler;

void print_usage(std::FILE* stream) {
  std::fputs(
      "flow_scheduler_bench — SYNTHETIC scheduling benchmark\n"
      "\n"
      "Usage: flow_scheduler_bench [options]\n"
      "  --flows <n>                number of flows (default 4000)\n"
      "  --priority-classes <n>     priority classes (default 4)\n"
      "  --fairness-groups <n>      fairness groups (default 4)\n"
      "  --deadline-density <f>     fraction with deadlines, 0..1 (default 0.5)\n"
      "  --dependency-density <f>   fraction with a dependency, 0..1 (default 0.25)\n"
      "  --concurrency <n>          resource max_overlap (default 8)\n"
      "  --capacity <n>             service units per interval (default 64)\n"
      "  --interval <ticks>         interval length in ticks (default 1000)\n"
      "  --quantum <n>              service quantum per dispatch (default 4)\n"
      "  --work <n>                 base estimated work per flow (default 16)\n"
      "  --seed <n>                 deterministic workload seed (default 1)\n"
      "  --rounds <n>               maximum arbitration rounds (default 200000)\n"
      "  --durable <dir>            exercise the durable journal in <dir>\n"
      "  --sweep                    run the fixed dimension sweep instead of one point\n"
      "  --help                     print this message\n"
      "\n"
      "All measurements are SYNTHETIC: the workload is generated by this process.\n",
      stream);
}

bool parse_u64(const char* text, std::uint64_t& out) {
  if (text == nullptr || *text == '\0') {
    return false;
  }
  char* end = nullptr;
  const unsigned long long value = std::strtoull(text, &end, 10);
  if (end == nullptr || *end != '\0') {
    return false;
  }
  out = static_cast<std::uint64_t>(value);
  return true;
}

bool parse_double(const char* text, double& out) {
  if (text == nullptr || *text == '\0') {
    return false;
  }
  char* end = nullptr;
  const double value = std::strtod(text, &end);
  if (end == nullptr || *end != '\0') {
    return false;
  }
  out = value;
  return true;
}

void print_header() {
  std::printf("%-12s %8s %8s %8s %8s %8s %10s %10s %10s %10s %10s %10s %12s %12s %10s\n",
              "label", "flows", "prio", "groups", "deadline", "depends", "concurr",
              "admitted", "completed", "ambiguous", "dispatches", "preempt", "p50-wait",
              "p99-wait", "seconds");
}

void print_row(const BenchmarkParameters& parameters, const BenchmarkResult& result) {
  std::printf("%-12s %8llu %8llu %8llu %8.2f %8.2f %10llu %10llu %10llu %10llu %10llu %10llu "
              "%12llu %12llu %10.3f\n",
              result.label.c_str(),
              static_cast<unsigned long long>(parameters.flow_count),
              static_cast<unsigned long long>(parameters.priority_classes),
              static_cast<unsigned long long>(parameters.fairness_groups),
              parameters.deadline_density, parameters.dependency_density,
              static_cast<unsigned long long>(parameters.concurrency),
              static_cast<unsigned long long>(result.flows_admitted),
              static_cast<unsigned long long>(result.flows_completed),
              static_cast<unsigned long long>(result.flows_ambiguous),
              static_cast<unsigned long long>(result.dispatches),
              static_cast<unsigned long long>(result.preemptions),
              static_cast<unsigned long long>(result.wait_p50_ticks),
              static_cast<unsigned long long>(result.wait_p99_ticks), result.wall_seconds);
  std::fflush(stdout);
}

int run_one(const BenchmarkParameters& parameters) {
  const Result<BenchmarkResult> result = run_synthetic_benchmark(parameters);
  if (!result.ok()) {
    std::fprintf(stderr, "benchmark failed: %s\n", result.error().to_string().c_str());
    return 1;
  }
  print_row(parameters, result.value());
  std::printf("detail: %s completions/s=%.0f service-units/s=%.0f rounds/s=%.0f "
              "starvation-boosts=%llu deadline-misses=%llu max-continuous-wait=%llu\n",
              result.value().detail.c_str(), result.value().completions_per_second,
              result.value().service_units_per_second, result.value().rounds_per_second,
              static_cast<unsigned long long>(result.value().starvation_boosts),
              static_cast<unsigned long long>(result.value().deadline_misses),
              static_cast<unsigned long long>(result.value().max_continuous_wait_ticks));
  return result.value().converged ? 0 : 2;
}

}  // namespace

int main(int argc, char** argv) {
  BenchmarkParameters parameters;
  // The command line default is smaller than the library default so that a bare
  // invocation reports a measurement within a few seconds.
  parameters.flow_count = 4'000;
  bool sweep = false;
  for (int index = 1; index < argc; ++index) {
    const std::string flag = argv[index];
    const bool has_value = index + 1 < argc;
    const char* value = has_value ? argv[index + 1] : nullptr;
    if (flag == "--help") {
      print_usage(stdout);
      return 0;
    }
    if (flag == "--sweep") {
      sweep = true;
      continue;
    }
    auto require_value = [&flag, has_value]() {
      if (!has_value) {
        std::fprintf(stderr, "missing value for %s\n", flag.c_str());
        return false;
      }
      return true;
    };
    if (flag == "--flows") {
      if (!require_value() || !parse_u64(value, parameters.flow_count)) {
        print_usage(stderr);
        return 2;
      }
      ++index;
    } else if (flag == "--priority-classes") {
      if (!require_value() || !parse_u64(value, parameters.priority_classes)) {
        print_usage(stderr);
        return 2;
      }
      ++index;
    } else if (flag == "--fairness-groups") {
      if (!require_value() || !parse_u64(value, parameters.fairness_groups)) {
        print_usage(stderr);
        return 2;
      }
      ++index;
    } else if (flag == "--deadline-density") {
      if (!require_value() || !parse_double(value, parameters.deadline_density)) {
        print_usage(stderr);
        return 2;
      }
      ++index;
    } else if (flag == "--dependency-density") {
      if (!require_value() || !parse_double(value, parameters.dependency_density)) {
        print_usage(stderr);
        return 2;
      }
      ++index;
    } else if (flag == "--concurrency") {
      if (!require_value() || !parse_u64(value, parameters.concurrency)) {
        print_usage(stderr);
        return 2;
      }
      ++index;
    } else if (flag == "--capacity") {
      if (!require_value() || !parse_u64(value, parameters.capacity_per_interval)) {
        print_usage(stderr);
        return 2;
      }
      ++index;
    } else if (flag == "--interval") {
      if (!require_value() || !parse_u64(value, parameters.interval_ticks)) {
        print_usage(stderr);
        return 2;
      }
      ++index;
    } else if (flag == "--quantum") {
      if (!require_value() || !parse_u64(value, parameters.service_quantum)) {
        print_usage(stderr);
        return 2;
      }
      ++index;
    } else if (flag == "--work") {
      if (!require_value() || !parse_u64(value, parameters.estimated_work)) {
        print_usage(stderr);
        return 2;
      }
      ++index;
    } else if (flag == "--seed") {
      if (!require_value() || !parse_u64(value, parameters.seed)) {
        print_usage(stderr);
        return 2;
      }
      ++index;
    } else if (flag == "--rounds") {
      if (!require_value() || !parse_u64(value, parameters.max_rounds)) {
        print_usage(stderr);
        return 2;
      }
      ++index;
    } else if (flag == "--durable") {
      if (!require_value()) {
        print_usage(stderr);
        return 2;
      }
      parameters.durable = true;
      parameters.durability_directory = value;
      ++index;
    } else {
      std::fprintf(stderr, "unknown option: %s\n", flag.c_str());
      print_usage(stderr);
      return 2;
    }
  }

  std::printf("flow_scheduler_bench %s — SYNTHETIC workload, no physical network involved\n",
              version_string());
  print_header();

  if (!sweep) {
    return run_one(parameters);
  }

  // The sweep varies one dimension at a time around the supplied base point,
  // so it stays tractable for any --flows value instead of hard-coding absolute
  // populations that may be far larger than the caller asked for.
  const std::uint64_t base_flows = parameters.flow_count == 0 ? 1 : parameters.flow_count;
  const std::uint64_t small_flows = base_flows > 8 ? base_flows / 8 : 1;
  const std::uint64_t large_flows =
      base_flows > (kMaxFlows / 2) ? kMaxFlows : base_flows * 2;
  const std::uint64_t base_priorities =
      parameters.priority_classes == 0 ? 1 : parameters.priority_classes;
  const std::uint64_t base_groups =
      parameters.fairness_groups == 0 ? 1 : parameters.fairness_groups;
  const std::uint64_t base_concurrency =
      parameters.concurrency == 0 ? 1 : parameters.concurrency;

  const std::uint64_t flow_counts[] = {small_flows, base_flows, large_flows};
  const std::uint64_t priority_counts[] = {1, base_priorities, base_priorities * 4};
  const std::uint64_t group_counts[] = {1, base_groups, base_groups * 8};
  const double deadline_densities[] = {0.0, 0.5, 1.0};
  const double dependency_densities[] = {0.0, 0.5, 1.0};
  const std::uint64_t concurrency_levels[] = {1, base_concurrency, base_concurrency * 8};

  int exit_code = 0;
  for (const std::uint64_t flows : flow_counts) {
    BenchmarkParameters point = parameters;
    point.flow_count = flows;
    exit_code |= run_one(point);
  }
  for (const std::uint64_t classes : priority_counts) {
    BenchmarkParameters point = parameters;
    point.priority_classes = classes;
    exit_code |= run_one(point);
  }
  for (const std::uint64_t groups : group_counts) {
    BenchmarkParameters point = parameters;
    point.fairness_groups = groups;
    exit_code |= run_one(point);
  }
  for (const double density : deadline_densities) {
    BenchmarkParameters point = parameters;
    point.deadline_density = density;
    exit_code |= run_one(point);
  }
  for (const double density : dependency_densities) {
    BenchmarkParameters point = parameters;
    point.dependency_density = density;
    exit_code |= run_one(point);
  }
  for (const std::uint64_t concurrency : concurrency_levels) {
    BenchmarkParameters point = parameters;
    point.concurrency = concurrency;
    exit_code |= run_one(point);
  }
  return exit_code;
}
